Naive Bayes classifiers are a collection of classification algorithms based on Bayes’ Theorem. It is not a single algorithm but a family of algorithms where all of them share a common principle, i.e. every pair of features being classified is independent of each other

**Bayes’ Theorem**
 It is used to find the probability of an event, based on prior knowledge of conditions that might be related to that event.
 P(A|B) = P(B|A)P(A) / P(B)
where,
P(A) and P(B) are the probabilities of events A and B
P(A|B) is the probability of event A when event B happens
P(B|A) is the probability of event B when A happens

# Practice1

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path="/content/Titanic.csv"
df=pd.read_csv(path)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked"],axis="columns",inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [ ]:
target=df.Survived
inputs=df.drop('Survived',axis="columns")

In [ ]:
dummies=pd.get_dummies(inputs.Sex).astype(int)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [ ]:
inputs=pd.concat([inputs,dummies],axis="columns")
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [ ]:
inputs.drop("Sex",axis="columns", inplace=True)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.Age[:10]

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)

In [ ]:
len(X_train)

712

In [ ]:
X_train

Pclass        Age      Fare  female  male
588       3  22.000000    8.0500       0     1
36        3  29.699118    7.2292       0     1
249       2  54.000000   26.0000       0     1
441       3  20.000000    9.5000       0     1
355       3  28.000000    9.5000       0     1
..      ...        ...       ...     ...   ...
535       2   7.000000   26.2500       1     0
464       3  29.699118    8.0500       0     1
150       2  51.000000   12.5250       0     1
698       1  49.000000  110.8833       0     1
616       3  34.000000   14.4000       0     1

[712 rows x 5 columns]

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB().fit(X_train,y_train)

In [ ]:
model.score(X_test,y_test)

0.7821229050279329

In [ ]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
y_test[:10]

491    0
23     1
525    0
828    1
492    0
652    0
631    0
715    0
748    0
145    0
Name: Survived, dtype: int64

In [ ]:
model.predict_proba(X_test[:10])

array([[0.98756772, 0.01243228],
       [0.90583945, 0.09416055],
       [0.9899891 , 0.0100109 ],
       [0.98930688, 0.01069312],
       [0.90861395, 0.09138605],
       [0.9876367 , 0.0123633 ],
       [0.98931612, 0.01068388],
       [0.98700789, 0.01299211],
       [0.84973599, 0.15026401],
       [0.96786121, 0.03213879]])

# Practice2

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path="/content/email.csv"
df=pd.read_csv(path)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.groupby("Category").describe()

Message         \
                 count unique   
Category                        
ham               4825   4516   
spam               747    641   
{"mode":"full"       1      1   

                                                                        
                                                              top freq  
Category                                                                
ham                                        Sorry, I'll call later   30  
spam            Please call our customer service representativ...    4  
{"mode":"full"                                    isActive:false}    1

In [11]:
df['spam']=df["Category"].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
model=CountVectorizer()
X_train_count=model.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
from sklearn.naive_bayes import MultinomialNB
models=MultinomialNB()
models.fit(X_train_count,y_train)

MultinomialNB()

In [20]:
emails=['hey maran, can we watch movie together',
        'Upto 20% discount on parking, exclusive offer just for you. Dont miss the reward']
emails_count=model.transform(emails)
model.predict(emails_count)

AttributeError: 'CountVectorizer' object has no attribute 'predict'